/* Runtime inventory: evaluates the same script order as index.html in a non-rendering DOM.
   This checks data completeness; it is not a browser or visual QA test. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),dist=path.join(root,'dist');
function node(){return {dataset:{},style:{},children:[],textContent:'',value:'',innerHTML:'',classList:{add(){},remove(){},toggle(){},contains(){return false}},append(){},prepend(){},appendChild(){},replaceChildren(){},after(){},remove(){},setAttribute(){},removeAttribute(){},getAttribute(){return ''},hasAttribute(){return false},addEventListener(){},querySelector(){return node()},querySelectorAll(){return []},closest(){return null},getBoundingClientRect(){return {width:1200,height:800}},scrollIntoView(){},showModal(){},close(){}}}
const nodes=new Map(),get=s=>{if(!nodes.has(s))nodes.set(s,node());return nodes.get(s)};
const document={querySelector:get,querySelectorAll:()=>[],getElementById:get,createElement:node,createTextNode:node,createTreeWalker:()=>({nextNode:()=>null}),addEventListener(){},body:node(),documentElement:node()};
const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k)};
const ctx=vm.createContext({document,Option:function(){return node()},console,URL,URLSearchParams,localStorage:storage,location:{href:'https://heysyu84.github.io/jatlas/'},navigator:{},setTimeout:()=>0,clearTimeout(){},queueMicrotask(){},requestAnimationFrame:()=>0,history:{pushState(){},replaceState(){}},crypto:require('node:crypto').webcrypto});
ctx.window=ctx;ctx.innerWidth=1280;ctx.matchMedia=()=>({matches:false,addEventListener(){}});ctx.addEventListener=()=>{};ctx.scrollTo=()=>{};
function suppressRender(source){let start=source.indexOf('function render(){');if(start<0)throw Error('render not found');let i=start+'function render(){'.length,depth=1; // Original function is one physical line.
const end=source.indexOf('\n',i);return source.slice(0,start)+'function render(){}'+source.slice(end)}
const scripts=[...fs.readFileSync(path.join(dist,'index.html'),'utf8').matchAll(/<script[^>]+src="([^"?]+)(?:\?[^"]*)?"/g)].map(m=>m[1]);
for(const file of scripts){if(file.startsWith('vendor/')||file==='weather.js')continue;let source=fs.readFileSync(path.join(dist,file),'utf8');if(file==='app.js')source=suppressRender(source);try{vm.runInContext(source,ctx,{filename:file})}catch(e){throw new Error(file+': '+e.stack)}}
const result=vm.runInContext(`({places:samples.map(p=>({...p,photo:photoForPlace(p),guide:tokyoVisitGuides[p.id]||null,coordinates:pointLocations[p.id]||null,ja:{name:translateText(p.name,true),description:translateText(p.description||'',true),activity:translateText(p.activity||'',true)},mapEmbed:googleDetailURL(p,true),mapExternal:googleDetailURL(p,false)})),prefectures:allPrefs.map(pref=>({pref,places:samples.filter(p=>p.pref===pref).length,foods:foodsForPref(pref).map(f=>{const canonical=globalThis.JATLAS_CANONICAL_FOOD_PHOTO?.(pref,f.name)||null;return {...f,photo:canonical||addedFoodPhotos[f.name]||null,image:canonical?.src||foodDetails[f.name]?.image||null}}),events:eventsForPref(pref),routes:routeTemplates.filter(r=>r.pref===pref)})),heroes:designPhotos,safety:(globalThis.JATLAS_CONTENT_SAFETY||{tombstones:[],duplicates:[],removedIds:[]})})`,ctx);
const outfile=process.argv[2]||path.join(root,'audits/runtime-inventory.json');fs.writeFileSync(outfile,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({prefectures:result.prefectures.length,places:result.places.length,foods:result.prefectures.reduce((n,p)=>n+p.foods.length,0),routes:result.prefectures.reduce((n,p)=>n+p.routes.length,0),output:outfile}));
module.exports={ctx,result};
