"""Build the runtime patch from exact-source metadata and explicit review decisions."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1];out=root/'audits';dist=root/'dist'
# Retain explicit visual review overrides when exact-source data is regenerated.
review_marker='/* Nagoya photo report: actual subject and composition checked before intermediate publication. */'
previous=(dist/'photo-qa-review.js').read_text() if (dist/'photo-qa-review.js').exists() else ''
reviewed_tail=review_marker+previous.split(review_marker,1)[1] if review_marker in previous else ''

localized=json.loads((out/'localized-photos.json').read_text());localized={k:v for k,v in localized.items() if 'error' not in v and (dist/v['src']).is_file()}
aliases=json.loads((dist/'image-migration-report.json').read_text())['fallback_aliases']
metrics=json.loads((out/'photo-audit.json').read_text())['entries']
contain=set(e['photo']['src'] for e in metrics if e.get('photo') and e.get('width') and (e['width']/e['height']<.8 or e['width']/e['height']>2.5))
contain.update(v['src'] for v in localized.values() if v['width']/v['height']<.8 or v['width']/v['height']>2.5)
s='/* Generated by tools/build-photo-qa.py. Exact source matching only. */\n'
s+='const photoQaLocal='+json.dumps(localized,ensure_ascii=False,separators=(',',':'))+';\n'
s+='const photoQaAliases='+json.dumps(aliases,ensure_ascii=False,separators=(',',':'))+';\n'
s+='const photoQaContain=new Set('+json.dumps(sorted(contain),ensure_ascii=False)+');\n'
s+='''const photoQaJapanese={'사진 준비 중':'写真準備中'};
const photoQaPendingPlaces=new Set([1208,2906,3203]);
const photoQaPendingFoods=new Set(['이모니','오시마 우유·아시타바 간식','이십세기배','도사 아카우시','미즈타키','요부코 오징어 활어회']);
function photoQaFilename(source){try{return decodeURIComponent((source||'').split('/wiki/File:')[1]||'').replaceAll('_',' ')}catch{return ''}}
function photoQaSource(source){const name=photoQaFilename(source);return photoQaAliases[name]?'https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(photoQaAliases[name].replaceAll(' ','_')):source}
const photoQaSrcChanges=new Map();
for(const pic of [...Object.values(tokyoPhotos),...Object.values(designPhotos),...Object.values(addedFoodPhotos),...regionalCatalog.flatMap(r=>[...Object.values(r.photos||{}),...Object.values(r.foodPhotos||{}),r.hero].filter(Boolean))]){
 const key=photoQaFilename(pic.source),local=photoQaLocal[key];
 if(local&&/^https?:/.test(pic.src||'')){photoQaSrcChanges.set(pic.src,local.src);Object.assign(pic,{...local,alt:pic.alt})}
 pic.source=photoQaSource(pic.source);
 if(photoQaContain.has(pic.src))pic.fit='contain';
}
for(const info of Object.values(foodDetails)){if(photoQaSrcChanges.has(info.image))info.image=photoQaSrcChanges.get(info.image)}
const photoQaOriginalPhotoForPlace=photoForPlace;
photoForPlace=function(p){return p&&!photoQaPendingPlaces.has(p.id)?photoQaOriginalPhotoForPlace(p):null};
const photoQaWithheldSources=new Set([...photoQaPendingPlaces].map(id=>tokyoPhotos[id]?.src).filter(Boolean));
for(const [key,hero] of Object.entries(designPhotos)){
 if(!photoQaWithheldSources.has(hero.src))continue;
 const replacement=samples.find(p=>(p.pref===key||p.area===key)&&photoForPlace(p));
 if(replacement)designPhotos[key]={...photoForPlace(replacement)};else delete designPhotos[key];
}
for(const name of photoQaPendingFoods){delete addedFoodPhotos[name];if(foodDetails[name])delete foodDetails[name].image;for(const r of regionalCatalog)if(r.foodPhotos)delete r.foodPhotos[name]}
for(const r of routeTemplates){const p=r.days.flatMap(d=>d.places).map(id=>samples.find(p=>p.id===id)).find(p=>photoForPlace(p));const pic=photoForPlace(p);r.image=pic?.src||'';r.imageAlt=pic?.alt||''}
const photoQaRenderFoods=renderFoods;
renderFoods=function(){photoQaRenderFoods();for(const card of document.querySelectorAll('.foodCard')){
 const img=card.querySelector('.foodPhoto');if(img&&photoQaContain.has(img.getAttribute('src')))img.dataset.photoFit='contain';
 if(photoQaPendingFoods.has(card.dataset.foodName)&&!card.querySelector('.photoPending')){img?.remove();const note=document.createElement('div');note.className='photoPending';note.textContent='사진 준비 중';card.prepend(note)}
}if(typeof localize==='function')localize()};
{
 const host=document.querySelector('#photoCreditList');
 for(const a of host.querySelectorAll('a'))a.href=photoQaSource(a.href);
 for(const pic of Object.values(photoQaLocal)){
  const row=document.createElement('p');row.className='photoAttribution';row.setAttribute('translate','no');
  const a=document.createElement('a');a.href=pic.source;a.target='_blank';a.rel='noopener';a.textContent=pic.filename;
  row.append(a,document.createTextNode(' · '+pic.author+' · '+pic.license+' · WebP / resized'));
  if(pic.licenseUrl){const l=document.createElement('a');l.href=pic.licenseUrl;l.target='_blank';l.rel='noopener';l.textContent=' '+pic.license;row.append(l)}host.append(row);
 }
}
'''
(dist/'photo-qa-review.js').write_text(s+'\n'+reviewed_tail)
print('Generated photo module',len(localized),'exact localizations')
